providers = ['go']

[phases.setup]
nixPkgs = [
    # '...',
    'go',
    'gcc',
    'templ'
]

[phases.install]
cmds = [
    'go generate .',
    'go get .'
]

[phases.build]
cmds = [
    'CGO_ENABLED=1 go build -o ./out ./main.go'
]

# [start]
# cmd = ''
