// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package database

import (
	"context"
)

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT request_hash, response_body, status_code FROM idempotency_keys
WHERE user_id = ? AND key_hash = ?
`

type GetIdempotencyRecordParams struct {
	UserID  string
	KeyHash string
}

type GetIdempotencyRecordRow struct {
	RequestHash  string
	ResponseBody string
	StatusCode   int64
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (GetIdempotencyRecordRow, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyRecord, arg.UserID, arg.KeyHash)
	var i GetIdempotencyRecordRow
	err := row.Scan(&i.RequestHash, &i.ResponseBody, &i.StatusCode)
	return i, err
}

const insertIdempotencyResponse = `-- name: InsertIdempotencyResponse :exec
INSERT INTO idempotency_keys (user_id, key_hash, request_hash, response_body, status_code, created_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
`

type InsertIdempotencyResponseParams struct {
	UserID       string
	KeyHash      string
	RequestHash  string
	ResponseBody string
	StatusCode   int64
}

func (q *Queries) InsertIdempotencyResponse(ctx context.Context, arg InsertIdempotencyResponseParams) error {
	_, err := q.db.ExecContext(ctx, insertIdempotencyResponse,
		arg.UserID,
		arg.KeyHash,
		arg.RequestHash,
		arg.ResponseBody,
		arg.StatusCode,
	)
	return err
}
