// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Plan struct {
	ID   int64
	Name string
	User string
}

type PlanAccess struct {
	ID     int64
	PlanID int64
	User   string
}

type Resource struct {
	ID           int64
	Title        string
	ResourceType int64
	Content      interface{}
	PlanID       int64
}

type Task struct {
	ID          int64
	PlanID      int64
	Date        string
	Title       string
	Subtitle    interface{}
	Description interface{}
	IsComplete  int64
}

type Template struct {
	ID          int64
	PlanID      int64
	Title       string
	Subtitle    interface{}
	Description interface{}
}
