// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type IdempotencyKey struct {
	ID           int64
	UserID       string
	KeyHash      string
	ResponseBody string
	StatusCode   int64
	CreatedAt    string
	RequestHash  string
}

type Plan struct {
	ID        int64
	Name      string
	User      string
	UpdatedAt string
	DeletedAt sql.NullString
}

type PlanAccess struct {
	ID        int64
	PlanID    int64
	User      string
	UpdatedAt string
	DeletedAt sql.NullString
}

type Resource struct {
	ID           int64
	Title        string
	ResourceType int64
	Content      interface{}
	PlanID       int64
	UpdatedAt    string
	DeletedAt    sql.NullString
}

type Task struct {
	ID          int64
	PlanID      int64
	Date        string
	Title       string
	Subtitle    interface{}
	Description interface{}
	IsComplete  int64
	UpdatedAt   string
	DeletedAt   sql.NullString
}

type Template struct {
	ID          int64
	PlanID      int64
	Title       string
	Subtitle    interface{}
	Description interface{}
	UpdatedAt   string
	DeletedAt   sql.NullString
}
