// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: plans.sql

package database

import (
	"context"
)

const createPlan = `-- name: CreatePlan :exec
INSERT INTO plans (
    name,
    user
) VALUES (
    ?1,
    ?2
)
`

type CreatePlanParams struct {
	Name string
	User string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) error {
	_, err := q.db.ExecContext(ctx, createPlan, arg.Name, arg.User)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans
WHERE id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id
             WHERE p.id = ?1 AND (p.user = ?2 OR pa.user = ?2))
`

type DeletePlanParams struct {
	ID     int64
	UserId string
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) error {
	_, err := q.db.ExecContext(ctx, deletePlan, arg.ID, arg.UserId)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT 
id, name, user 
FROM plans
WHERE id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id
             WHERE p.id = ?1 AND (p.user = ?2 OR pa.user = ?2))
`

type GetPlanParams struct {
	ID     int64
	UserId string
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, arg.ID, arg.UserId)
	var i Plan
	err := row.Scan(&i.ID, &i.Name, &i.User)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT 
id, name, user 
FROM plans
WHERE id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id
             WHERE p.user = ?1 OR pa.user = ?1)
`

func (q *Queries) ListPlans(ctx context.Context, userid string) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(&i.ID, &i.Name, &i.User); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans 
SET name = ?1
WHERE id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id
             WHERE p.id = ?2 AND (p.user = ?3 OR pa.user = ?3))
`

type UpdatePlanParams struct {
	Name   string
	ID     int64
	UserId string
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan, arg.Name, arg.ID, arg.UserId)
	return err
}
