// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: plans.sql

package database

import (
	"context"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    name,
    user,
    updated_at
) VALUES (
    ?1,
    ?2,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
RETURNING id, name, user, updated_at, deleted_at
`

type CreatePlanParams struct {
	Name string
	User string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan, arg.Name, arg.User)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.User,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
UPDATE plans
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE plans.deleted_at IS NULL AND plans.id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE p.id = ?1 AND (p.user = ?2 OR pa.user = ?2))
`

type DeletePlanParams struct {
	ID     int64
	UserId string
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) error {
	_, err := q.db.ExecContext(ctx, deletePlan, arg.ID, arg.UserId)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT 
p.id, p.name, p.user, p.updated_at, p.deleted_at 
FROM plans p
WHERE p.deleted_at IS NULL AND p.id IN (SELECT p2.id FROM plans as p2
             LEFT OUTER JOIN plan_access as pa ON p2.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE p2.id = ?1 AND (p2.user = ?2 OR pa.user = ?2) AND p2.deleted_at IS NULL)
`

type GetPlanParams struct {
	ID     int64
	UserId string
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, arg.ID, arg.UserId)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.User,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT DISTINCT
p.id, p.name, p.user, p.updated_at, p.deleted_at
FROM plans p
LEFT OUTER JOIN plan_access pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
WHERE (p.user = ?1 OR pa.user = ?1)
AND p.deleted_at IS NULL
`

func (q *Queries) ListPlans(ctx context.Context, userid string) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.User,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansSync = `-- name: ListPlansSync :many
SELECT DISTINCT
p.id, p.name, p.user, p.updated_at, p.deleted_at
FROM plans p
LEFT OUTER JOIN plan_access pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
WHERE (p.user = ?1 OR pa.user = ?1)
AND p.deleted_at IS NULL
AND (?2 = '' OR p.updated_at >= ?2)
AND (?3 = '' OR (p.updated_at > ?3 OR (p.updated_at = ?3 AND p.id > ?4)))
ORDER BY p.updated_at ASC, p.id ASC
LIMIT ?5
`

type ListPlansSyncParams struct {
	UserID       string
	UpdatedSince interface{}
	CursorTs     interface{}
	CursorID     int64
	LimitCount   int64
}

func (q *Queries) ListPlansSync(ctx context.Context, arg ListPlansSyncParams) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansSync,
		arg.UserID,
		arg.UpdatedSince,
		arg.CursorTs,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.User,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans 
SET name = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE plans.deleted_at IS NULL AND plans.id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE p.id = ?2 AND (p.user = ?3 OR pa.user = ?3))
`

type UpdatePlanParams struct {
	Name   string
	ID     int64
	UserId string
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan, arg.Name, arg.ID, arg.UserId)
	return err
}

const updatePlanIfMatch = `-- name: UpdatePlanIfMatch :execrows
UPDATE plans 
SET name = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE plans.deleted_at IS NULL AND plans.id IN (SELECT p.id FROM plans as p
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE p.id = ?2 AND (p.user = ?3 OR pa.user = ?3))
AND plans.updated_at = ?4
`

type UpdatePlanIfMatchParams struct {
	Name          string
	ID            int64
	UserId        string
	BaseUpdatedAt string
}

func (q *Queries) UpdatePlanIfMatch(ctx context.Context, arg UpdatePlanIfMatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlanIfMatch,
		arg.Name,
		arg.ID,
		arg.UserId,
		arg.BaseUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
