// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package database

import (
	"context"
	"strings"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    plan_id,
    title,
    date,
    subtitle,
    description,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
RETURNING id, plan_id, date, title, subtitle, description, is_complete, updated_at, deleted_at
`

type CreateTaskParams struct {
	PlanID      int64
	Title       string
	Date        string
	Subtitle    interface{}
	Description interface{}
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.PlanID,
		arg.Title,
		arg.Date,
		arg.Subtitle,
		arg.Description,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Date,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.IsComplete,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaskFromTemplate = `-- name: CreateTaskFromTemplate :one
INSERT INTO tasks (
    plan_id,
    title,
    date,
    subtitle,
    description,
    updated_at
) 
SELECT t.plan_id, t.title, ?1, t.subtitle, t.description, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM templates as t
WHERE t.deleted_at IS NULL AND t.id IN (SELECT t2.id FROM templates as t2
             INNER JOIN plans as p ON t2.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t2.id = ?2 AND t2.deleted_at IS NULL AND (p.user = ?3 OR pa.user = ?3))
RETURNING id, plan_id, date, title, subtitle, description, is_complete, updated_at, deleted_at
`

type CreateTaskFromTemplateParams struct {
	Date       string
	TemplateId int64
	UserId     string
}

func (q *Queries) CreateTaskFromTemplate(ctx context.Context, arg CreateTaskFromTemplateParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTaskFromTemplate, arg.Date, arg.TemplateId, arg.UserId)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Date,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.IsComplete,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND id IN (SELECT t.id FROM tasks as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?1 AND (p.user = ?2 OR pa.user = ?2))
`

type DeleteTaskParams struct {
	ID     int64
	UserId string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.UserId)
	return err
}

const getTask = `-- name: GetTask :one
SELECT 
t.id, t.plan_id, t.date, t.title, t.subtitle, t.description, t.is_complete, t.updated_at, t.deleted_at
FROM tasks as t
INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
WHERE t.id = ?1 AND t.deleted_at IS NULL AND (p.user = ?2 OR pa.user = ?2)
`

type GetTaskParams struct {
	ID     int64
	UserId string
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.UserId)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Date,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.IsComplete,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTasksByDate = `-- name: GetTasksByDate :many
SELECT
  t.id, t.plan_id, t.date, t.title, t.subtitle, t.description, t.is_complete, t.updated_at, t.deleted_at
FROM
  tasks AS t
WHERE
  t.deleted_at IS NULL
  AND t.date = ?1
  AND t.plan_id IN (
    SELECT
      p.id
    FROM
      plans AS p
      LEFT OUTER JOIN plan_access AS pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
    WHERE
      p.id = ?2
      AND p.deleted_at IS NULL
      AND (
        p.user = ?3 OR pa.user = ?3
      )
  )
`

type GetTasksByDateParams struct {
	Date   string
	PlanId int64
	UserId string
}

func (q *Queries) GetTasksByDate(ctx context.Context, arg GetTasksByDateParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByDate, arg.Date, arg.PlanId, arg.UserId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Date,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.IsComplete,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByPlan = `-- name: GetTasksByPlan :many
SELECT
  t.id, t.plan_id, t.date, t.title, t.subtitle, t.description, t.is_complete, t.updated_at, t.deleted_at
FROM
  tasks AS t
WHERE
  t.deleted_at IS NULL
  AND t.plan_id IN (
    SELECT
      p.id
    FROM
      plans AS p
      LEFT OUTER JOIN plan_access AS pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
    WHERE
      p.id = ?1
      AND p.deleted_at IS NULL
      AND (
        p.user = ?2 OR pa.user = ?2
      )
  )
ORDER BY t.date ASC
`

type GetTasksByPlanParams struct {
	PlanId int64
	UserId string
}

func (q *Queries) GetTasksByPlan(ctx context.Context, arg GetTasksByPlanParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByPlan, arg.PlanId, arg.UserId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Date,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.IsComplete,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPlanAndDates = `-- name: ListTasksByPlanAndDates :many
SELECT
  t.id, t.plan_id, t.date, t.title, t.subtitle, t.description, t.is_complete, t.updated_at, t.deleted_at
FROM
  tasks AS t
INNER JOIN plans AS p ON t.plan_id = p.id AND p.deleted_at IS NULL
LEFT OUTER JOIN plan_access AS pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
WHERE
  t.deleted_at IS NULL
  AND t.plan_id = ?1
  AND (p.user = ?2 OR pa.user = ?2)
  AND t.date IN (/*SLICE:dates*/?)
ORDER BY t.date ASC
`

type ListTasksByPlanAndDatesParams struct {
	PlanID int64
	UserID string
	Dates  []string
}

func (q *Queries) ListTasksByPlanAndDates(ctx context.Context, arg ListTasksByPlanAndDatesParams) ([]Task, error) {
	query := listTasksByPlanAndDates
	var queryParams []interface{}
	queryParams = append(queryParams, arg.PlanID)
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Dates) > 0 {
		for _, v := range arg.Dates {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:dates*/?", strings.Repeat(",?", len(arg.Dates))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:dates*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Date,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.IsComplete,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPlanSync = `-- name: ListTasksByPlanSync :many
SELECT
  t.id, t.plan_id, t.date, t.title, t.subtitle, t.description, t.is_complete, t.updated_at, t.deleted_at
FROM
  tasks AS t
WHERE
  t.deleted_at IS NULL
  AND t.plan_id = ?1
  AND t.plan_id IN (
    SELECT
      p.id
    FROM
      plans AS p
      LEFT OUTER JOIN plan_access AS pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
    WHERE
      p.id = ?1
      AND p.deleted_at IS NULL
      AND (
        p.user = ?2 OR pa.user = ?2
      )
  )
AND (COALESCE(?3, '') = '' OR t.updated_at >= ?3)
AND (COALESCE(?4, '') = '' OR (t.updated_at > ?4 OR (t.updated_at = ?4 AND t.id > ?5)))
ORDER BY t.updated_at ASC, t.id ASC
LIMIT ?6
`

type ListTasksByPlanSyncParams struct {
	PlanID       int64
	UserID       string
	UpdatedSince interface{}
	CursorTs     interface{}
	CursorID     int64
	LimitCount   int64
}

func (q *Queries) ListTasksByPlanSync(ctx context.Context, arg ListTasksByPlanSyncParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByPlanSync,
		arg.PlanID,
		arg.UserID,
		arg.UpdatedSince,
		arg.CursorTs,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Date,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.IsComplete,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIsCompleteTask = `-- name: SetIsCompleteTask :exec
UPDATE tasks 
SET is_complete = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND id IN (SELECT t.id FROM tasks as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?2 AND (p.user = ?3 OR pa.user = ?3))
`

type SetIsCompleteTaskParams struct {
	IsComplete int64
	ID         int64
	UserId     string
}

func (q *Queries) SetIsCompleteTask(ctx context.Context, arg SetIsCompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, setIsCompleteTask, arg.IsComplete, arg.ID, arg.UserId)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET title = ?1, subtitle = ?2, date = ?3, description = ?4,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND id IN (SELECT t.id FROM tasks as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?5 AND (p.user = ?6 OR pa.user = ?6))
`

type UpdateTaskParams struct {
	Title       string
	Subtitle    interface{}
	Date        string
	Description interface{}
	ID          int64
	UserId      string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Subtitle,
		arg.Date,
		arg.Description,
		arg.ID,
		arg.UserId,
	)
	return err
}

const updateTaskIfMatch = `-- name: UpdateTaskIfMatch :execrows
UPDATE tasks 
SET title = ?1, subtitle = ?2, date = ?3, description = ?4,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE deleted_at IS NULL AND id IN (SELECT t.id FROM tasks as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?5 AND (p.user = ?6 OR pa.user = ?6))
AND tasks.updated_at = ?7
`

type UpdateTaskIfMatchParams struct {
	Title         string
	Subtitle      interface{}
	Date          string
	Description   interface{}
	ID            int64
	UserId        string
	BaseUpdatedAt string
}

func (q *Queries) UpdateTaskIfMatch(ctx context.Context, arg UpdateTaskIfMatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTaskIfMatch,
		arg.Title,
		arg.Subtitle,
		arg.Date,
		arg.Description,
		arg.ID,
		arg.UserId,
		arg.BaseUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
