// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: templates.sql

package database

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (
    plan_id,
    title,
    subtitle,
    description,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
RETURNING id, plan_id, title, subtitle, description, updated_at, deleted_at
`

type CreateTemplateParams struct {
	PlanID      int64
	Title       string
	Subtitle    interface{}
	Description interface{}
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate,
		arg.PlanID,
		arg.Title,
		arg.Subtitle,
		arg.Description,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
UPDATE templates
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id IN (SELECT t.id FROM templates as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?1 AND t.deleted_at IS NULL AND (p.user = ?2 OR pa.user = ?2))
`

type DeleteTemplateParams struct {
	ID     int64
	UserId string
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, arg.ID, arg.UserId)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT 
t.id, t.plan_id, t.title, t.subtitle, t.description, t.updated_at, t.deleted_at
FROM templates as t
INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
WHERE t.id = ?1 AND t.deleted_at IS NULL AND (p.user = ?2 OR pa.user = ?2)
`

type GetTemplateParams struct {
	ID     int64
	UserId string
}

func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, arg.ID, arg.UserId)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Title,
		&i.Subtitle,
		&i.Description,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTemplatesByPlan = `-- name: GetTemplatesByPlan :many
SELECT
  t.id, t.plan_id, t.title, t.subtitle, t.description, t.updated_at, t.deleted_at
FROM
  templates AS t
WHERE
  t.deleted_at IS NULL
  AND t.plan_id IN (
    SELECT
      p.id
    FROM
      plans AS p
      LEFT OUTER JOIN plan_access AS pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
    WHERE
      p.id = ?1
      AND (
        p.user = ?2 OR pa.user = ?2
      )
      AND p.deleted_at IS NULL
  )
ORDER BY t.title ASC
`

type GetTemplatesByPlanParams struct {
	PlanId int64
	UserId string
}

func (q *Queries) GetTemplatesByPlan(ctx context.Context, arg GetTemplatesByPlanParams) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, getTemplatesByPlan, arg.PlanId, arg.UserId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByPlanSync = `-- name: ListTemplatesByPlanSync :many
SELECT
  t.id, t.plan_id, t.title, t.subtitle, t.description, t.updated_at, t.deleted_at
FROM
  templates AS t
WHERE
  t.deleted_at IS NULL
  AND t.plan_id = ?1
  AND t.plan_id IN (
    SELECT
      p.id
    FROM
      plans AS p
      LEFT OUTER JOIN plan_access AS pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
    WHERE
      p.id = ?1
      AND (
        p.user = ?2 OR pa.user = ?2
      )
      AND p.deleted_at IS NULL
  )
AND (?3 = '' OR t.updated_at >= ?3)
AND (?4 = '' OR (t.updated_at > ?4 OR (t.updated_at = ?4 AND t.id > ?5)))
ORDER BY t.updated_at ASC, t.id ASC
LIMIT ?6
`

type ListTemplatesByPlanSyncParams struct {
	PlanID       int64
	UserID       string
	UpdatedSince interface{}
	CursorTs     interface{}
	CursorID     int64
	LimitCount   int64
}

func (q *Queries) ListTemplatesByPlanSync(ctx context.Context, arg ListTemplatesByPlanSyncParams) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesByPlanSync,
		arg.PlanID,
		arg.UserID,
		arg.UpdatedSince,
		arg.CursorTs,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates 
SET title = ?1, subtitle = ?2, description = ?3,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id IN (SELECT t.id FROM templates as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?4 AND t.deleted_at IS NULL AND (p.user = ?5 OR pa.user = ?5))
`

type UpdateTemplateParams struct {
	Title       string
	Subtitle    interface{}
	Description interface{}
	ID          int64
	UserId      string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.ID,
		arg.UserId,
	)
	return err
}

const updateTemplateIfMatch = `-- name: UpdateTemplateIfMatch :execrows
UPDATE templates 
SET title = ?1, subtitle = ?2, description = ?3,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id IN (SELECT t.id FROM templates as t
             INNER JOIN plans as p ON t.plan_id = p.id AND p.deleted_at IS NULL
             LEFT OUTER JOIN plan_access as pa ON p.id = pa.plan_id AND pa.deleted_at IS NULL
             WHERE t.id = ?4 AND t.deleted_at IS NULL AND (p.user = ?5 OR pa.user = ?5))
AND templates.updated_at = ?6
`

type UpdateTemplateIfMatchParams struct {
	Title         string
	Subtitle      interface{}
	Description   interface{}
	ID            int64
	UserId        string
	BaseUpdatedAt string
}

func (q *Queries) UpdateTemplateIfMatch(ctx context.Context, arg UpdateTemplateIfMatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTemplateIfMatch,
		arg.Title,
		arg.Subtitle,
		arg.Description,
		arg.ID,
		arg.UserId,
		arg.BaseUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
